// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: combat.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace attributes.combat
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FightInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"atk")]
        public int Atk { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"def")]
        public int Def { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_hp")]
        public int MaxHp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cur_hp")]
        public int CurHp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"max_mp")]
        public int MaxMp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"cur_mp")]
        public int CurMp { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"speed")]
        public int Speed { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"critical_rate")]
        public int CriticalRate { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"critical_damage")]
        public int CriticalDamage { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"evasion_rate")]
        public int EvasionRate { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"hit_rate")]
        public int HitRate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FightResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public long Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"damage")]
        public int Damage { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_hp")]
        public int CurHp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"max_hp")]
        public int MaxHp { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
