// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace attributes.common
{

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INVALID_PARAM")]
        InvalidParam = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NOT_FOUND")]
        NotFound = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PERMISSION_DENIED")]
        PermissionDenied = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_ERROR")]
        ServerError = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
