// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: scene_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace service.scene
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestEnterDefaultScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
            public int ErrorCode { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"entity_scene_info")]
            public global::attributes.scene.EntitySceneInfo EntitySceneInfo { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"scene_info")]
            public global::attributes.scene.SceneInfo SceneInfo { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestEnterScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scene_id")]
        public int SceneId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scene_gid")]
        public int SceneGid { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
            public int ErrorCode { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
            public long Uid { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"scene_info")]
            public global::attributes.scene.SceneInfo SceneInfo { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"direction")]
        public int Direction { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stop_move")]
        public bool StopMove { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"global_id")]
            public long GlobalId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"position")]
            public global::attributes.scene.Position Position { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestUpdatePos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos")]
        public global::attributes.scene.Position Pos { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"scene_info")]
            public global::attributes.scene.SceneInfo SceneInfo { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
            public long Uid { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestUseSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id")]
        public int SkillId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
            public int ErrorCode { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
            public long Uid { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"skill_id")]
            public int SkillId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"result")]
            public global::System.Collections.Generic.List<global::attributes.combat.FightResult> Results { get; } = new global::System.Collections.Generic.List<global::attributes.combat.FightResult>();

            [global::ProtoBuf.ProtoMember(5, Name = @"npc_result")]
            public global::System.Collections.Generic.List<global::attributes.combat.FightResult> NpcResults { get; } = new global::System.Collections.Generic.List<global::attributes.combat.FightResult>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ResponsePos : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_code")]
            public int ErrorCode { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
            public long Uid { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"skill_id")]
            public int SkillId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"global_skill_id")]
            public long GlobalSkillId { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"pos")]
            public global::attributes.scene.Position Pos { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestGetScenePlayers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"scene_id")]
            public int SceneId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"scene_gid")]
            public int SceneGid { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"player_count")]
            public int PlayerCount { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"players")]
            public global::System.Collections.Generic.List<global::attributes.scene.PlayerSceneInfo> Players { get; } = new global::System.Collections.Generic.List<global::attributes.scene.PlayerSceneInfo>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestLeaveScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestFightInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public long Uid { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Response : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
            public long Uid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"fight_info")]
            public global::attributes.combat.FightInfo FightInfo { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestPathFind : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"z")]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseUpdateView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"in_view_entities")]
        public global::System.Collections.Generic.List<global::attributes.scene.EntitySceneInfo> InViewEntities { get; } = new global::System.Collections.Generic.List<global::attributes.scene.EntitySceneInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"out_view_entities")]
        public global::System.Collections.Generic.List<global::attributes.scene.EntitySceneInfo> OutViewEntities { get; } = new global::System.Collections.Generic.List<global::attributes.scene.EntitySceneInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseLeaveView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"global_id")]
        public long GlobalId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseEnterView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"in_view_entity")]
        public global::attributes.scene.EntitySceneInfo InViewEntity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseUpdateNpcView : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"leave_npcs")]
        public global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo> LeaveNpcs { get; } = new global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"enter_npcs")]
        public global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo> EnterNpcs { get; } = new global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"update_npcs")]
        public global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo> UpdateNpcs { get; } = new global::System.Collections.Generic.List<global::attributes.scene.NpcSceneInfo>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
